apiVersion: batch/v1
kind: Job
metadata:
  name: build-and-deploy-job
  namespace: devops-pipeline
spec:
  template:
    spec:
      containers:
        - name: docker-build
          image: docker:dind
          command: ["/bin/sh", "-c"]
          args:
            - |
              git clone --single-branch --branch $(GIT_BRANCH) https://github.com/marciok/sample-app-docker.git /tmp/repo && \
              cd /tmp/repo && \
              echo "Building Docker image..." && \
              docker build -t myapp:$(GIT_BRANCH) . 

              # Run dockerd with insecure registry flag if it's not already managed by systemctl
              echo "Starting Docker daemon with insecure registry..."
              dockerd --insecure-registry 10.245.251.103:5000 &

              # Wait a moment to ensure the daemon starts
              sleep 5

              # Log in to the Harbor registry using --password-stdin
              echo "Logging into Harbor registry..."
              echo harbor_registry_password | docker login http://10.245.251.103:5000 -u harbor_registry_user --password-stdin && \

              # Tag and push the image
              echo "Tagging and pushing the image..."
              docker tag myapp:$(GIT_BRANCH) $(IMAGE_HOST)/your-image:$(GIT_BRANCH) && \
              docker push $(IMAGE_HOST)/your-image:$(GIT_BRANCH)
              - name: docker-socket
              mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
