apiVersion: batch/v1
kind: Job
metadata:
  name: build-and-deploy-job
  namespace: devops-pipeline
spec:
  template:
    spec:
      containers:
        - name: buildah-build
          image: quay.io/buildah/stable:latest
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              git clone --single-branch --branch $(GIT_BRANCH) https://github.com/marciok/sample-app-docker.git /tmp/repo && \
              cd /tmp/repo && \
              echo "Building Docker image..." && \
              buildah bud -t myapp:$(GIT_BRANCH) . && \
              echo "Logging into Harbor registry..." && \
              echo $HARBOR_PASSWORD | buildah login --username $HARBOR_USERNAME --password-stdin $(IMAGE_HOST) && \
              echo "Tagging and pushing the image..." && \
              buildah tag myapp:$(GIT_BRANCH) $(IMAGE_HOST)/your-image:$(GIT_BRANCH) && \
              buildah push --tls-verify=false $(IMAGE_HOST)/your-image:$(GIT_BRANCH)
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
