apiVersion: batch/v1
kind: Job
metadata:
  name: build-and-deploy-job
  namespace: devops-pipeline
spec:
  template:
    spec:
      containers:
        - name: docker-build
          image: docker:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              git clone --single-branch --branch $(GIT_BRANCH) https://github.com/marciok/sample-app-docker.git /tmp/repo && \
              cd /tmp/repo && \
              echo "Building Docker image..." && \
              docker build -t myapp:$(GIT_BRANCH) . && \
              echo "Logging into Harbor registry..." && \
              echo "ARE YOU SEEING THIS 3?"
              docker login $(IMAGE_HOST) -u harbor_registry_user -p harbor_registry_password && \
              echo "Tagging and pushing the image..." && \
              docker tag myapp:$(GIT_BRANCH) $(IMAGE_HOST)/your-image:$(GIT_BRANCH) && \
              docker push $(IMAGE_HOST)/your-image:$(GIT_BRANCH)
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
