apiVersion: batch/v1
kind: Job
metadata:
  name: build-and-deploy-job
  namespace: devops-pipeline
spec:
  template:
    spec:
      containers:
        - name: docker-build
          image: docker:dind
          command: ["/bin/sh", "-c"]
          args:
            - |
              git clone --single-branch --branch $(GIT_BRANCH) https://github.com/marciok/sample-app-docker.git /tmp/repo && \
              cd /tmp/repo && \
              echo "Building Docker image..." && \
              docker build -t myapp:$(GIT_BRANCH) . 

              # Add the insecure registry to Docker daemon configuration
              echo "Updating Docker daemon configuration for insecure registry..."
              mkdir -p /etc/docker
              echo '{
                "insecure-registries": ["10.245.251.103:5000"]
              }' > /etc/docker/daemon.json

              # Restart Docker to apply the new settings
              echo "Restarting Docker service..."
              systemctl restart docker

              # Log in to the Harbor registry
              echo "Logging into Harbor registry..."
              docker login http://10.245.251.103:5000 -u harbor_registry_user -p harbor_registry_password && \

              # Tag and push the image
              echo "Tagging and pushing the image..."
              docker tag myapp:$(GIT_BRANCH) $(IMAGE_HOST)/your-image:$(GIT_BRANCH) && \
              docker push $(IMAGE_HOST)/your-image:$(GIT_BRANCH)
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
