apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  namespace: devops-pipeline
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command: ["/bin/sh", "-c"]
        args: [
          "/kaniko/executor --context=git://github.com/marciok/sample-app-docker.git --destination=10.245.20.5:30003/library/my-app:${GIT_BRANCH} --skip-tls-verify"
        ]
        volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
      - name: docker-config
        secret:
          secretName: kaniko-docker-config