apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        args: [
          "--dockerfile=/workspace/Dockerfile",
          "--context=git://github.com/marciok/sample-app-docker.git",
          "--destination=10.245.251.103:5000/my-app:latest",
          "--insecure-registry=10.245.251.103:5000"
        ]
        volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
      - name: kaniko-secret
        secret:
          secretName: kaniko-secret
