apiVersion: batch/v1
kind: Job
metadata:
  name: build-and-deploy-job
  namespace: devops-pipeline
spec:
  template:
    spec:
      containers:
      - name: podman
        image: quay.io/podman/stable:latest  # Use the official Podman image
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Set up Podman with the necessary environment variables
            export REGISTRY=http://10.245.251.103:5000
            export IMAGE_NAME=myapp:latest
            export PROJECT=project

            # Clone the repository and build the image
            git clone --single-branch --branch $(GIT_BRANCH) https://github.com/marciok/sample-app-docker.git /tmp/repo
            cd /tmp/repo
            podman build -t ${IMAGE_NAME} .

            # Login to the registry
            podman login --username=harbor_registry_user --password=harbor_registry_password ${REGISTRY}

            # Tag and push the image
            podman tag ${IMAGE_NAME} ${REGISTRY}/${PROJECT}/${IMAGE_NAME}
            podman push ${REGISTRY}/${PROJECT}/${IMAGE_NAME}
      restartPolicy: Never
