apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: devops-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: myapp-container
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: regcred
