- op: add
  path: /spec/rules/-
  value:
    host: street-light-manifesto.melhorbanco.digital
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: street-light-manifesto-service
              port:
                number: 8080
