- op: add
  path: /spec/rules/-
  value:
    host: test-teardown-preview.melhorbanco.digital
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: test-teardown-preview-service
              port:
                number: 8080
