- op: add
  path: /spec/rules/-
  value:
    host: update-image-7d4434af76d49ae41d3ab34f1371e2730ce52604.melhorbanco.digital
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: update-image-7d4434af76d49ae41d3ab34f1371e2730ce52604-service
              port:
                number: 8080
