resources:
  - ../../base
namePrefix: increase-timeout-
labels:
  - includeSelectors: true
    pairs:
      app: increase-timeout
images:
  - name: myapp-container
    newName: ghcr.io/marciok/sample-app-docker
    newTag: increase-timeout
patches:
  - target:
      kind: Service
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          external-dns.alpha.kubernetes.io/hostname: increase-timeout.melhorbanco.digital
