apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    namespace: devops-pipeline
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: 1.15.0
    chart: harbor
    helm:
      releaseName: harbor
      values: |
        expose:
          type: nodePort
          tls:
            enabled: true
  project: default