apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    namespace: devops-pipeline
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: 1.15.0
    chart: harbor
    helm:
      releaseName: harbor
      values: |
        externalURL: https://127.0.0.1:30003
        expose:
          type: nodePort
          tls:
            auto:
              commonName: 127.0.0.1
          nodePort:
            ports:
              https:
                nodePort: 30003
  project: default