apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.2
    chart: ingress-nginx
    helm:
      values: |
        controller:
          publishService:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-pipeline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
