resources:
  - ../../base
namePrefix: blink-182-
labels:
  - includeSelectors: true
    pairs:
      app: blink-182
images:
  - name: myapp-container
    newName: ghcr.io/marciok/sample-app-docker
    newTag: blink-182