resources:
  - ../../base
namePrefix: smash-mouth-
labels:
  - pairs:
      app: smash-mouth
configMapGenerator:
  - name: env
    namespace: devops-pipeline
    literals:
      - GIT_BRANCH=smash-mouth
      - IMAGE_HOST=10.245.199.74:5443
    options:
      disableNameSuffixHash: true
images:
  - name: myapp-container
    newName: https://harbor-registry.devops-pipeline.svc.cluster.local/my-app
    newTag: smash-mouth
patches:
  - target:
      kind: Job
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: smash-mouth-env
  # - target:
  #     kind: Ingress
  #   patch: |-
  #     - op: add
  #       path: /spec/rules/-
  #       value:
  #         host: smash-mouth.comparacar-dev.com.br
  #         http:
  #           paths:
  #             - path: /
  #               pathType: Prefix
  #               backend:
  #                 service:
  #                   name: smash-mouth-myapp
  #                   port:
  #                     number: 3000
